name: Build Headscale Build Image

on:
  push:
    branches:
      - build
  workflow_dispatch:

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Build headscale-build image
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -f Dockerfile.build -t ghcr.io/socoldkiller/headscale-build:dev .
          docker push ghcr.io/socoldkiller/headscale-build:dev

